#!/bin/bash

# script for opening the following apps in the preferred workspaces (saving a little bit of time and effort), I open these there application every morning in the same workspaces so why not automate it.

# Applications
TERMINAL="kitty"
BROWSER="brave"
MAIL_APP="thunderbird"

# === Workspace 8 - Mail
hyprctl dispatch workspace 8
sleep 1
$MAIL_APP &
sleep 3

# === Workspace 2 — Brave with personal profile ===
hyprctl dispatch workspace 2
  $BROWSER --profile-directory="Default" &
sleep 2

# === Workspace 1 — Terminal with tmux ===
hyprctl dispatch workspace 1
# Launch terminal 
$TERMINAL -e tmux


