# Hyprpaper Configuration
# Author: Binoy Manoj
# GitHub: https://github.com/binoymanoj
# Last Updated: 2026-02-21

preload = ~/Pictures/Wallpapers/aesthetic-coding-wallpaper.jpg
wallpaper = ,~/Pictures/Wallpapers/aesthetic-coding-wallpaper.jpg
