# Hyprpaper Configuration
# Author: Binoy Manoj
# GitHub: https://github.com/binoymanoj
# Last Updated: 2026-05-14

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/aesthetic-coding-wallpaper.jpg
    fit_mode = cover
}
